// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgiksbzwggsstpqqnuev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnaWtzYnp3Z2dzc3RwcXFudWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDQzNDEsImV4cCI6MjA1NzE4MDM0MX0.Q65QPFq-0KZcpTnktNvt221ngOdha19WbPgau5eeR5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);